Repository depromeet/TeumTeum-Android, pull requests merged in 2024-01, with the labels that each got.

#19 [FEAT#18] 흔들 때 진동 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/di/RepositoryModule.kt
  app/src/main/java/com/teumteum/teumteum/di/ServiceModule.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/TeumTeumFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/shake/ShakeDetector.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 우남, FEAT

#25 [FEAT/#21] 온보딩 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/MyApp.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/adapter/OnBoardingViewPagerAdapter.kt
  app/src/main/res/color/color_text_button_primary_selector.xml
  app/src/main/res/drawable/button_cta_active.xml
  app/src/main/res/drawable/button_cta_disabled.xml
  app/src/main/res/drawable/button_cta_pressed.xml
  app/src/main/res/drawable/button_cta_selector.xml
  app/src/main/res/drawable/viewpager_dot_active.xml
  app/src/main/res/drawable/viewpager_dot_disabled.xml
  app/src/main/res/drawable/viewpager_dot_selector.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_onboarding_viewpager.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build-logic/.gitignore
  core/base/src/main/res/font/pretendard_black.otf
  core/base/src/main/res/font/pretendard_bold.otf
  core/base/src/main/res/font/pretendard_extrabold.otf
  core/base/src/main/res/font/pretendard_extralight.otf
  core/base/src/main/res/font/pretendard_light.otf
  core/base/src/main/res/font/pretendard_medium.otf
  core/base/src/main/res/font/pretendard_regular.otf
  core/base/src/main/res/font/pretendard_semibold.otf
  core/base/src/main/res/font/pretendard_thin.otf
  core/base/src/main/res/font/teumteum_font.xml
  core/base/src/main/res/layout/layout_common_appbar.xml
  core/base/src/main/res/values-night/colors.xml
  core/base/src/main/res/values/attrs.xml
  core/base/src/main/res/values/colors.xml
  core/base/src/main/res/values/themes.xml
  core/domain/src/main/java/com/teumteum/domain/entity/CommonViewPagerEntity.kt
Labels: 세연, FEAT, MERGE

#29 [FEAT/#16] 카드 전면 커스텀 뷰 제작
  app/src/main/java/com/teumteum/teumteum/util/custom/view/FrontCardView.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/model/FrontCard.kt
  app/src/main/res/drawable/ic_card_penguin.xml
  app/src/main/res/drawable/shape_rect0_grey_50.xml
  app/src/main/res/drawable/shape_rect10_grey_500.xml
  app/src/main/res/drawable/shape_rect12_grey_900.xml
  app/src/main/res/drawable/shape_rect16_grey_50.xml
  app/src/main/res/drawable/shape_rect4_grey_800.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_teum_teum.xml
  app/src/main/res/layout/item_recommend_meet.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/res/values/attrs.xml
  core/base/src/main/res/values/themes.xml
Labels: 우남, FEAT, UI

#31 [FEAT/#24] 모임 생성 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/WebviewFragment.kt
  app/src/main/java/com/teumteum/teumteum/di/NetworkStatus.kt
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimAddress.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateName.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateTopic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimDateTime.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimIntroduce.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimPeople.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/FrontCardView.kt
  app/src/main/res/drawable-night/ic_floating_btn.xml
  app/src/main/res/drawable-night/ic_system_minus.xml
  app/src/main/res/drawable-night/ic_system_plus.xml
  app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  app/src/main/res/drawable/ic_floating_btn.xml
  app/src/main/res/drawable/ic_system_fill.xml
  app/src/main/res/drawable/ic_system_minus.xml
  app/src/main/res/drawable/ic_system_plus.xml
  app/src/main/res/drawable/progress_bar_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_moim.xml
  app/src/main/res/layout/fragment_webview.xml
  app/src/main/res/menu/main_bottom_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/build/kotlin/compileKotlin/cacheable/last-build.bin
  build-logic/convention/build/kotlin/compileKotlin/local-state/build-history.bin
  build-logic/convention/build/libs/convention.jar
  core/base/src/main/java/com/teumteum/base/component/compose/TmDivider.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Color.kt
Labels: 민서, FEAT, ADD, UI

#28 [FEAT/#11] 모임 검색 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/di/RepositoryModule.kt
  app/src/main/java/com/teumteum/teumteum/di/ServiceModule.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/KeywordAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchViewModel.kt
  app/src/main/res/drawable/shape_outline_level3_200dp.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_keyword_list.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/last-build.bin
  build-logic/convention/build/kotlin/compileKotlin/local-state/build-history.bin
  build-logic/convention/build/kotlin/conventionjar-classes.txt
  build-logic/convention/build/libs/convention.jar
  core/base/src/main/java/com/teumteum/base/util/extension/ContextExtension.kt
  core/base/src/main/res/values/themes.xml
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseGroup.kt
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/GroupService.kt
  core/domain/src/main/java/com/teumteum/domain/entity/Meeting.kt
  core/domain/src/main/java/com/teumteum/domain/repository/GroupRepository.kt
Labels: 강민 🦖, UI

#34 [FEAT/#24] 모임 생성 구현
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimAddress.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateName.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateTopic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimDateTime.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimIntroduce.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimPeople.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/res/layout/fragment_moim.xml
  app/src/main/res/menu/main_bottom_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/java/com/teumteum/base/component/compose/TmScaffold.kt
  core/base/src/main/java/com/teumteum/base/component/compose/TmSnackBar.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Color.kt
  core/base/src/main/res/drawable/ic_arrow_left_l.xml
  core/base/src/main/res/drawable/ic_arrow_left_spacer.xml
Labels: 민서, ADD, CHORE

#38 [FEAT/#36] 친해지기 온보딩
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/TeumTeumFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/shake/ShakeOnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/shake/ShakeOnBoardingAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/shake/ShakeOnboarding.kt
  app/src/main/res/drawable-night/ic_shake_onboarding_card.xml
  app/src/main/res/drawable-night/ic_shake_onboarding_interest.xml
  app/src/main/res/drawable-night/ic_shake_onboarding_location.xml
  app/src/main/res/drawable/ic_shake_onboarding_card.xml
  app/src/main/res/drawable/ic_shake_onboarding_interest.xml
  app/src/main/res/drawable/ic_shake_onboarding_location.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_teum_teum.xml
  app/src/main/res/layout/item_shake_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: 우남, FEAT, UI

#40 [FEAT/#32] 모임 참여 확인 & 완료 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupMeetCheckActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupMeetCheckViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupMeetCompleteActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupMeetCompleteViewModel.kt
  app/src/main/res/color/selector_check_box_group.xml
  app/src/main/res/drawable-night/ic_check_box_default.xml
  app/src/main/res/drawable/ic_check_box_default.xml
  app/src/main/res/drawable/ic_check_box_select.xml
  app/src/main/res/drawable/ic_meet_complete.xml
  app/src/main/res/drawable/selector_check_box.xml
  app/src/main/res/drawable/shape_elevation_level1_8dp.xml
  app/src/main/res/layout/activity_group_meet_check.xml
  app/src/main/res/layout/activity_group_meet_complete.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/res/color/component_button_alternative_color.xml
  core/base/src/main/res/color/component_button_primary_color.xml
  core/base/src/main/res/drawable/component_button_fill_alternative.xml
  core/base/src/main/res/drawable/component_button_fill_primary.xml
  core/base/src/main/res/values/styles.xml
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseGroup.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseMeetingArea.kt
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/GroupService.kt
  core/domain/src/main/java/com/teumteum/domain/repository/GroupRepository.kt
Labels: 강민 🦖, FEAT, ADD, UI

#43 [FEAT/#24] 모임 생성 구현
  app/src/main/java/com/teumteum/teumteum/WebviewFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimAddress.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateTopic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/WebViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/WebviewFragment.kt
  app/src/main/res/drawable-night/icon_share.xml
  app/src/main/res/drawable/icon_share.xml
  app/src/main/res/layout/fragment_webview.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/last-build.bin
  build-logic/convention/build/kotlin/compileKotlin/local-state/build-history.bin
  build-logic/convention/build/kotlin/conventionjar-classes.txt
  build-logic/convention/build/libs/convention.jar
  core/base/src/main/java/com/teumteum/base/component/compose/TmDivider.kt
  core/base/src/main/java/com/teumteum/base/component/compose/TmIndicator.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Color.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Type.kt
  gradle/libs.versions.toml
Labels: 민서, FEAT, UI

#48 [FEAT/#46] AuthInterceptor 구현
  app/src/main/java/com/teumteum/teumteum/di/DataStoreModule.kt
  app/src/main/java/com/teumteum/teumteum/di/RetrofitModule.kt
  app/src/main/java/com/teumteum/teumteum/di/qualifier/InterceptorQualifier.kt
  core/data/src/main/java/com/teumteum/data/local/TeumTeumDataStoreImpl.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseAuthToken.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseGroup.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseMeetingArea.kt
  core/data/src/main/java/com/teumteum/data/remote/AuthInterceptor.kt
  core/domain/src/main/java/com/teumteum/domain/TeumTeumDataStore.kt
  core/domain/src/main/java/com/teumteum/domain/entity/Meeting.kt
  gradle/libs.versions.toml
Labels: 강민 🦖, FEAT

#51 [FEAT/#46] 실서버 연결
  app/src/main/java/com/teumteum/teumteum/di/ServiceModule.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupMeetCheckActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupMeetCheckViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupMeetCompleteActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/ic_meet_complete.xml
  app/src/main/res/drawable/ic_search_empty.xml
  app/src/main/res/layout/activity_group_meet_complete.xml
  app/src/main/res/layout/activity_search.xml
  core/base/src/main/java/com/teumteum/base/util/extension/IntentExtension.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseGroup.kt
Labels: 강민 🦖, FEAT, ADD

#55 [ADD/#53] DataStore에 사용자 정보 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/di/RepositoryModule.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashViewModel.kt
  app/src/main/res/layout/activity_splash.xml
  core/data/src/main/java/com/teumteum/data/local/TeumTeumDataStoreImpl.kt
  core/data/src/main/java/com/teumteum/data/repository/UserRepositoryImpl.kt
  core/domain/src/main/java/com/teumteum/domain/TeumTeumDataStore.kt
  core/domain/src/main/java/com/teumteum/domain/entity/UserInfo.kt
  core/domain/src/main/java/com/teumteum/domain/repository/UserRepository.kt
Labels: 세연, ADD

#58 [FEAT/#42] 회원가입 데이터 연결
  .github/workflows/pr_checker.yml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/di/RepositoryModule.kt
  app/src/main/java/com/teumteum/teumteum/di/ServiceModule.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SocialWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/finish/SignUpFinishActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/goal/GetGoalFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/intro/CardIntroActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/mbti/GetMbtiFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/MbtiModalBottomSheet.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/teumteum/teumteum/util/NetworkManager.kt
  app/src/main/res/layout/activity_social_webview.xml
  app/src/main/res/layout/fragment_preferred_area.xml
  app/src/main/res/values/arrays.xml
  build-logic/convention/src/main/java/com/teumteum/convention/src/main/kotlin/plugins/AndroidApplicationPlugin.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/teumteum/data/local/TeumTeumDataStoreImpl.kt
  core/data/src/main/java/com/teumteum/data/model/request/RequestUserInfo.kt
  core/data/src/main/java/com/teumteum/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/repository/UserRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/UserService.kt
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/teumteum/domain/TeumTeumDataStore.kt
  core/domain/src/main/java/com/teumteum/domain/entity/MoimEntity.kt
  core/domain/src/main/java/com/teumteum/domain/entity/SignUpResult.kt
  core/domain/src/main/java/com/teumteum/domain/entity/SocialLoginResult.kt
  core/domain/src/main/java/com/teumteum/domain/entity/UserInfo.kt
  core/domain/src/main/java/com/teumteum/domain/repository/AuthRepository.kt
  core/domain/src/main/java/com/teumteum/domain/repository/UserRepository.kt
Labels: 세연, FEAT, ADD

#61 [feat/#60] 카드 커스텀 뷰 앞면 클릭 리스너 추가
  app/src/main/java/com/teumteum/teumteum/util/custom/view/FrontCardView.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/model/FrontCard.kt
  app/src/main/res/values/ids.xml
Labels: 우남, FEAT

#64 [Feat/#52] 홈 메인화면 구현
  .github/workflows/pr_checker.yml
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/java/com/teumteum/teumteum/util/extension/DateUtil.kt
  app/src/main/res/drawable-night/ic_logo_title.xml
  app/src/main/res/drawable/ic_logo_title.xml
  app/src/main/res/drawable/shape_elevation_level2_4dp.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_group_list.xml
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/proto.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/subtypes.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/subtypes.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/supertypes.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/supertypes.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/counters.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.keystream.len
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.len
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/lookups.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/lookups.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/last-build.bin
  build-logic/convention/build/kotlin/compileKotlin/local-state/build-history.bin
  build-logic/convention/build/kotlin/conventionjar-classes.txt
  build-logic/convention/build/libs/convention.jar
  core/data/build.gradle.kts
  core/data/src/main/java/com/teumteum/data/model/response/ResponseGroup.kt
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/domain/src/main/java/com/teumteum/domain/enumSet/EnumTopic.kt
  core/domain/src/main/java/com/teumteum/domain/repository/GroupRepository.kt
Labels: 강민 🦖, FEAT, ADD, UI

#63 [Feat/#50] 대화 주제 뷰페이저 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/TopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/TopicAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/TopicViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/model/Topic.kt
  app/src/main/res/drawable-night/ic_balance_background_1.xml
  app/src/main/res/drawable-night/ic_balance_background_2.xml
  app/src/main/res/drawable-night/ic_balance_background_3.xml
  app/src/main/res/drawable-night/ic_balance_background_4.xml
  app/src/main/res/drawable-night/ic_balance_background_5.xml
  app/src/main/res/drawable/ic_balance_background_1.xml
  app/src/main/res/drawable/ic_balance_background_2.xml
  app/src/main/res/drawable/ic_balance_background_3.xml
  app/src/main/res/drawable/ic_balance_background_4.xml
  app/src/main/res/drawable/ic_balance_background_5.xml
  app/src/main/res/layout/activity_topic.xml
  app/src/main/res/layout/item_topic.xml
Labels: 우남, FEAT

#65 [FIX/#62] 코멘트 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SocialWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  core/base/src/main/res/values/themes.xml
  core/data/src/main/java/com/teumteum/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/repository/UserRepositoryImpl.kt
  core/domain/src/main/java/com/teumteum/domain/entity/UserInfo.kt
  core/domain/src/main/java/com/teumteum/domain/repository/AuthRepository.kt
  core/domain/src/main/java/com/teumteum/domain/repository/UserRepository.kt
Labels: 세연, FEAT, FIX

#70 [FEAT/#69] 홈 화면 다크/라이트 적용, 네비바 메뉴 수정
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/res/color/selector_bottom_menu.xml
  app/src/main/res/drawable-night/ic_bell.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/ic_bottom_navi_familiar.xml
  app/src/main/res/drawable/ic_bottom_navi_home.xml
  app/src/main/res/drawable/ic_bottom_navi_mypage.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recommend_meet.xml
  app/src/main/res/menu/main_bottom_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 우남, UI

#68 [FEAT/#67] 무한 스크롤 구현
  app/src/debug/java/com/teumteum/teumteum/FlipperSetUp.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/domain/src/main/java/com/teumteum/domain/repository/GroupRepository.kt
Labels: 강민 🦖, FEAT

#74 [feat/#73] 친해지기 온보딩 최초 1회 노출 제한
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/CharacterView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/SharedPreferenceManager.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/location/LocationActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/location/LocationViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/model/FamiliarOnBoarding.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/InterestView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/ShakeActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/ShakeDetector.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/model/InterestViewConfig.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/model/InterestViewData.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/model/Topic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/teumteum/shake/model/InterestViewData.kt
  app/src/main/java/com/teumteum/teumteum/util/PermissionUtils.kt
  app/src/main/res/layout/activity_location.xml
  app/src/main/res/layout/fragment_familiar.xml
  app/src/main/res/layout/fragment_teum_teum.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 우남, FEAT

#75 [FEAT/#66] 회원가입 과정에서의 카드 수정
  app/src/main/AndroidManifest.xml
  app/src/main/assets/docs_terms_location.html
  app/src/main/assets/docs_terms_private.html
  app/src/main/assets/docs_terms_service.html
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/AccessLocationActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SocialWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/interests/GetInterestFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashViewModel.kt
  app/src/main/res/drawable/shape_rect8_elevation_level01.xml
  app/src/main/res/layout/activity_access_location.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_terms.xml
  app/src/main/res/layout/activity_terms_webview.xml
  app/src/main/res/layout/fragment_card_fix.xml
  app/src/main/res/layout/fragment_get_goal.xml
  app/src/main/res/layout/fragment_get_name.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/java/com/teumteum/base/component/snackbar/ButtonSnackBar.kt
  core/base/src/main/java/com/teumteum/base/component/snackbar/DefaultSnackBar.kt
  core/base/src/main/java/com/teumteum/base/util/extension/ContextExtension.kt
  core/base/src/main/res/drawable/shape_rect12_button_default02.xml
  core/base/src/main/res/layout/snackbar_button.xml
  core/base/src/main/res/layout/snackbar_default.xml
  core/base/src/main/res/values/themes.xml
  core/domain/src/main/java/com/teumteum/domain/entity/UserInfo.kt
Labels: 세연, FEAT, FIX

#78 [ FIX/#66] 반복되는 상수 유틸로 분리
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/AccessLocationActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SocialWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/area/PreferredAreaFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/community/CommunityFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/interests/GetInterestFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/intro/CardIntroActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/job/CurrentJobFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/job/ReadyJobFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/mbti/GetMbtiFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/AreaModalBottomSheet.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/util/SigninUtils.kt
  app/src/main/java/com/teumteum/teumteum/util/SignupUtils.kt
  app/src/main/res/values/strings.xml
Labels: 세연, FIX, REFACTOR

#82 [FIX/#81] 바텀시트 및 스낵바 수정
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/mbti/GetMbtiFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/MbtiModalBottomSheet.kt
  core/base/src/main/java/com/teumteum/base/component/toast/DefaultToast.kt
  core/base/src/main/java/com/teumteum/base/util/extension/ContextExtension.kt
  core/base/src/main/res/layout/toast_default.xml
Labels: 세연, FIX

#80 [FEAT/#45] Argument 친구 목록 재사용 추가
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardChip.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/MeetingPagerItems.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendDetailScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendDetailViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/fragment/RecommendDetailFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/fragment/RecommendFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/EditCardViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/RecommendDetailViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/interests/GetInterestFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/AreaModalBottomSheet.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/MbtiModalBottomSheet.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/SingleModalBottomSheet.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/last-build.bin
  build-logic/convention/build/kotlin/compileKotlin/local-state/build-history.bin
  build-logic/convention/build/kotlin/conventionjar-classes.txt
  build-logic/convention/build/libs/convention.jar
  core/base/src/main/java/com/teumteum/base/component/compose/theme/TmInputField.kt
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/teumteum/data/repository/UserRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/UserService.kt
  core/domain/src/main/java/com/teumteum/domain/repository/UserRepository.kt
Labels: 민서, FEAT, FIX

#90 [ FEAT/#89] 화면 전환 애니메이션 디테일 수정
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupDetailActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/JoinFriendListActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/check/GroupMeetCheckActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/complete/GroupMeetCompleteActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendDetailScreen.kt
Labels: 강민 🦖, FEAT

#93 [REFACTORING/#92] 모임 검색 기능 & UX 개선
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
  app/src/main/res/layout/activity_search.xml
Labels: 강민 🦖, REFACTOR

#95 [FEAT/#94] 모임 없을 때 Empty 안내 추가
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/res/layout/activity_group_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 강민 🦖, FEAT, UI

#87 [Feat/#45] v1 구현 마무리
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateName.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateTopic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFinish.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimIntroduce.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/MeetingPagerItems.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/Pager1Content.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendDetailScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/fragment/RecommendDetailFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/SettingScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/SettingServiceScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/EditMyInfoFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/SettingFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/EditCardViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/RecommendDetailViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/SettingMeetingUiModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/SettingViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/res/drawable-night/ic_plus_fill.xml
  app/src/main/res/drawable-night/ic_suprise.xml
  app/src/main/res/drawable-night/ic_system_fill.xml
  app/src/main/res/drawable/ic_suprise.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Color.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Theme.kt
  core/data/src/main/java/com/teumteum/data/repository/UserRepositoryImpl.kt
  core/domain/src/main/java/com/teumteum/domain/entity/Friend.kt
Labels: 민서, FEAT, DEL, FIX

#97 [UI/#96] 모임 리스트 divider 색상 수정
  app/src/main/res/layout/item_group_list.xml
Labels: 강민 🦖, UI

#88 [FEAT/#85] 뒤로가기 콜백 및 마무리 작업
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/AccessLocationActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SocialWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/finish/SignUpFinishActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/intro/CardIntroActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/util/SignupUtils.kt
  app/src/main/java/com/teumteum/teumteum/util/callback/CustomBackPressedCallback.kt
  app/src/main/res/layout/activity_card_intro.xml
  app/src/main/res/layout/fragment_card_complete.xml
  app/src/main/res/layout/fragment_card_fix.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/res/anim/card_reverse_back.xml
  core/base/src/main/res/anim/card_reverse_front.xml
Labels: 세연, FEAT, ADD

#91 [FEAT/#76] 소개 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/di/RepositoryModule.kt
  app/src/main/java/com/teumteum/teumteum/di/ServiceModule.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/location/LocationActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/location/LocationViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/CharacterView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/ShakeActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/ShakeDetector.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/teumteum/teumteum/util/AuthUtils.kt
  app/src/main/java/com/teumteum/teumteum/util/IdMapper.kt
  app/src/main/res/drawable/ic_cat.xml
  app/src/main/res/layout/activity_introduce.xml
  app/src/main/res/layout/activity_location.xml
  app/src/main/res/layout/activity_neighbor.xml
  app/src/main/res/layout/custom_character_view.xml
  app/src/main/res/layout/item_introduce.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteNeighborDataSource.kt
  core/data/src/main/java/com/teumteum/data/model/request/RequestPostNeighborUser.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponsePostNeighborUser.kt
  core/data/src/main/java/com/teumteum/data/repository/NeighborRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/NeghborService.kt
  core/domain/src/main/java/com/teumteum/domain/entity/Friend.kt
  core/domain/src/main/java/com/teumteum/domain/entity/NeighborEntity.kt
  core/domain/src/main/java/com/teumteum/domain/entity/UserInfo.kt
  core/domain/src/main/java/com/teumteum/domain/repository/NeighborRepository.kt
Labels: 우남, FEAT

#99 [fix/#98] 모임 리스트 다크모드 대응
  app/src/main/res/layout/activity_group_list.xml
Labels: 강민 🦖, FIX, UI

#102 [FEAT/#101] 버튼 중복 클릭(이중 or 여러번) 방지 구현
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/CharacterView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/JoinFriendAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/check/GroupMeetCheckActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/complete/GroupMeetCompleteActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/KeywordAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/AccessLocationActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/area/PreferredAreaFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/character/CharacterListAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/community/CommunityFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/finish/SignUpFinishActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/intro/CardIntroActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/job/CurrentJobFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/job/ReadyJobFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/mbti/GetMbtiFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/AreaCityModalAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/AreaStreetModalAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/MbtiModalBottomSheet.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/SingleModalAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsActivity.kt
  core/base/src/main/java/com/teumteum/base/component/appbar/AppBarLayout.kt
  core/base/src/main/java/com/teumteum/base/component/snackbar/ButtonSnackBar.kt
  core/base/src/main/java/com/teumteum/base/util/extension/ViewExtension.kt
Labels: 강민 🦖, FEAT

#105 [Fix/#104] 다크모드&라이트 모드 설정
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupDetailActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimAddress.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateName.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimCreateTopic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimDateTime.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFinish.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimIntroduce.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/MeetingPagerItems.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/Pager1Content.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/fragment/RecommendDetailFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/fragment/RecommendFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/EditMyInfoScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/SettingScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/SettingServiceScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/SettingSignOutConfirmScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/SettingSignOutScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/EditMyInfoFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/ServiceFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/SettingFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/SignOutConfirmFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/SignOutFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/SettingMeetingUiModel.kt
  app/src/main/java/com/teumteum/teumteum/util/callback/CustomBackPressedCallback.kt
  app/src/main/res/layout/fragment_moim.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/java/com/teumteum/base/component/compose/TmScaffold.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Color.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Theme.kt
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/teumteum/data/repository/UserRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/UserService.kt
  core/domain/src/main/java/com/teumteum/domain/entity/Friend.kt
  core/domain/src/main/java/com/teumteum/domain/repository/UserRepository.kt
Labels: 민서, FIX, UI

#106 [FIX/#103] 온보딩/회원가입 1차 QA 대응
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/goal/GetGoalFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/interests/GetInterestFragment.kt
  app/src/main/res/drawable/ic_card_edit.xml
  app/src/main/res/drawable/ic_select_circle_24.xml
  app/src/main/res/drawable/ic_select_circle_24_fill.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_terms.xml
  app/src/main/res/layout/fragment_card_fix.xml
  app/src/main/res/layout/fragment_current_job.xml
  app/src/main/res/layout/fragment_current_school.xml
  app/src/main/res/layout/fragment_get_goal.xml
  app/src/main/res/layout/fragment_get_interest.xml
  app/src/main/res/layout/fragment_get_name.xml
  app/src/main/res/layout/fragment_ready_job.xml
  app/src/main/res/layout/item_onboarding_viewpager.xml
Labels: 세연, FIX

#109 [FEAT/#100] 친해지기 디테일 보충
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/CharacterView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/util/IdMapper.kt
  app/src/main/res/drawable-night/ic_check.xml
  app/src/main/res/drawable-night/ic_familiar_onboarding_card.xml
  app/src/main/res/drawable-night/ic_familiar_onboarding_interest.xml
  app/src/main/res/drawable-night/ic_familiar_onboarding_neighbor.xml
  app/src/main/res/drawable-night/ic_shake_onboarding_card.xml
  app/src/main/res/drawable-night/ic_shake_onboarding_interest.xml
  app/src/main/res/drawable-night/ic_shake_onboarding_location.xml
  app/src/main/res/drawable/ic_character_pink.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_familiar_onboarding_card.xml
  app/src/main/res/drawable/ic_familiar_onboarding_interest.xml
  app/src/main/res/drawable/ic_familiar_onboarding_neighbor.xml
  app/src/main/res/drawable/ic_shake_onboarding_card.xml
  app/src/main/res/drawable/ic_shake_onboarding_interest.xml
  app/src/main/res/drawable/ic_shake_onboarding_location.xml
  app/src/main/res/drawable/ic_teum_teum.xml
  app/src/main/res/drawable/ic_teumteum_logo.xml
  app/src/main/res/layout/activity_neighbor.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/custom_character_view.xml
  app/src/main/res/layout/item_familiar_onboarding.xml
  app/src/main/res/menu/main_bottom_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  core/base/src/main/res/values/themes.xml
Labels: 우남, FIX

#113 [FEAT/#112] 친해지기 뒤집기 애니메이션 적용
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/model/Topic.kt
  app/src/main/java/com/teumteum/teumteum/util/IdMapper.kt
  app/src/main/res/drawable-night/ic_back_balance_background_1.xml
  app/src/main/res/drawable-night/ic_back_balance_background_2.xml
  app/src/main/res/drawable-night/ic_back_balance_background_3.xml
  app/src/main/res/drawable-night/ic_back_balance_background_4.xml
  app/src/main/res/drawable-night/ic_back_balance_background_5.xml
  app/src/main/res/drawable-night/ic_front_balance_background_1.xml
  app/src/main/res/drawable-night/ic_front_balance_background_2.xml
  app/src/main/res/drawable-night/ic_front_balance_background_3.xml
  app/src/main/res/drawable-night/ic_front_balance_background_4.xml
  app/src/main/res/drawable-night/ic_front_balance_background_5.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_1.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_2.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_3.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_4.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_5.xml
  app/src/main/res/drawable/ic_back_balance_background_1.xml
  app/src/main/res/drawable/ic_back_balance_background_2.xml
  app/src/main/res/drawable/ic_back_balance_background_3.xml
  app/src/main/res/drawable/ic_back_balance_background_4.xml
  app/src/main/res/drawable/ic_back_balance_background_5.xml
  app/src/main/res/drawable/ic_front_balance_background_1.xml
  app/src/main/res/drawable/ic_front_balance_background_2.xml
  app/src/main/res/drawable/ic_front_balance_background_3.xml
  app/src/main/res/drawable/ic_front_balance_background_4.xml
  app/src/main/res/drawable/ic_front_balance_background_5.xml
  app/src/main/res/layout/item_introduce.xml
  app/src/main/res/layout/item_topic.xml
  core/domain/src/main/java/com/teumteum/domain/entity/Friend.kt
Labels: 우남, FEAT

#116 [UI/#115] 유저 리뷰하기 UI 구현
  app/src/main/res/drawable/ic_review.xml
  app/src/main/res/drawable/ic_review_finish.xml
  app/src/main/res/drawable/selector_circle_friend_review.xml
  app/src/main/res/drawable/shape_circle_bg_character.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/activity_review_finish.xml
  app/src/main/res/layout/activity_review_onboading.xml
  app/src/main/res/layout/fragment_review_friend_detail.xml
  app/src/main/res/layout/fragment_review_friend_select.xml
  app/src/main/res/layout/item_review_user.xml
  app/src/main/res/values/strings.xml
Labels: 강민 🦖, UI

#107 [Fix/#104] chip margin 수정 + 후면 커스텀뷰 연결
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupDetailActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimModifyFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimAddress.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimCreateName.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimCreateTopic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimDateTime.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimFinish.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimIntroduce.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimModify.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimPeople.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardChip.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/MeetingPagerItems.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/Pager1Content.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/EditMyInfoScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/EditCardViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/RecommendDetailViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/SettingViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/interests/GetInterestFragment.kt
  app/src/main/java/com/teumteum/teumteum/util/SignupUtils.kt
  app/src/main/res/drawable-night/ic_system_line.xml
  app/src/main/res/drawable/ic_system_line.xml
  app/src/main/res/layout/fragment_modify_moim.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/java/com/teumteum/base/component/compose/TmScaffold.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Color.kt
  core/base/src/main/res/drawable/ic_system_line.xml
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/GroupService.kt
  core/domain/src/main/java/com/teumteum/domain/repository/GroupRepository.kt
Labels: 민서, ADD, FIX

#117 [FEAT/#114] FCM 알림
  .github/workflows/pr_checker.yml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/config/TeumMessagingService.kt
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashViewModel.kt
  app/src/main/res/layout/item_onboarding_viewpager.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/java/com/teumteum/convention/src/main/kotlin/plugins/AndroidApplicationPlugin.kt
  build.gradle.kts
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/teumteum/data/local/TeumTeumDataStoreImpl.kt
  core/data/src/main/java/com/teumteum/data/model/request/RequestDeviceToken.kt
  core/data/src/main/java/com/teumteum/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/UserService.kt
  core/domain/src/main/java/com/teumteum/domain/TeumTeumDataStore.kt
  core/domain/src/main/java/com/teumteum/domain/repository/AuthRepository.kt
  gradle/libs.versions.toml
Labels: 세연, FEAT
