Repository depromeet/TeumTeum-Android, pull requests merged in 2024-02, with the labels that each got.

#121 [REFACTORING/#120] 모임 리스트 이미지 비율 수정
  app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListAdapter.kt
  app/src/main/res/layout/item_group_list.xml
Labels: 강민 🦖, REFACTOR

#122 [FIX/#118] 버전 코드, 친구 목록 아이콘 수정
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
  build-logic/convention/src/main/java/com/teumteum/convention/src/main/kotlin/Constants.kt
Labels: 민서, FIX

#123 [FEAT/#111] 대화 주제 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/di/RepositoryModule.kt
  app/src/main/java/com/teumteum/teumteum/di/RetrofitModule.kt
  app/src/main/java/com/teumteum/teumteum/di/ServiceModule.kt
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarDialogActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/InterestView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/ShakeActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicViewModel.kt
  app/src/main/java/com/teumteum/teumteum/util/ResMapper.kt
  app/src/main/res/drawable-night/ic_dialog_interest.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_1.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_2.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_3.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_4.xml
  app/src/main/res/drawable-night/l_ic_front_balance_background_5.xml
  app/src/main/res/drawable/ic_dialog_interest.xml
  app/src/main/res/layout/activity_familiar_dialog.xml
  app/src/main/res/layout/activity_neighbor.xml
  app/src/main/res/layout/activity_shake.xml
  app/src/main/res/layout/item_topic.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/res/font/nexa_bold.otf
  core/base/src/main/res/font/teumteum_font.xml
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteTopicDataSource.kt
  core/data/src/main/java/com/teumteum/data/interceptor/AuthInterceptor.kt
  core/data/src/main/java/com/teumteum/data/model/response/BalanceResponse.kt
  core/data/src/main/java/com/teumteum/data/model/response/StoryResponse.kt
  core/data/src/main/java/com/teumteum/data/repository/TopicRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/TopicService.kt
  core/domain/src/main/java/com/teumteum/domain/entity/TopicResponse.kt
  core/domain/src/main/java/com/teumteum/domain/repository/TopicRepository.kt
Labels: 우남, FEAT

#127 [FIX/#126] 취업준비생 유저 직업명 수정
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/res/values/strings.xml
Labels: 세연, FEAT

#128 [FIX/#118] 카드 뒷면 수정
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
Labels: 민서, FIX

#129 [FEAT/#124] 대화 주제 사용성 개선
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarDialogActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/InterestView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shake/model/InterestViewData.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/topic/TopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/ShakeTopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/ShakeTopicViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/shake/InterestView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/shake/ShakeDetector.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/shake/ShakeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/shake/model/InterestViewConfig.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/shake/model/InterestViewData.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/topic/TopicAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/topic/TopicFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/topic/model/Topic.kt
  app/src/main/res/layout/activity_shake_topic.xml
  app/src/main/res/layout/fragment_shake.xml
  app/src/main/res/layout/fragment_topic.xml
Labels: 우남, FEAT

#134 [ FIX/#131] 친해지기 런칭데이 QA
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarDialogActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/FamiliarFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/introduce/IntroduceAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/neighbor/NeighborViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/onboarding/FamiliarOnBoardingAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/ShakeTopicActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/ShakeTopicViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/shake/InterestView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/shake/ShakeDetector.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/shake/ShakeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/shake/model/InterestViewConfig.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/shake/model/InterestViewData.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/topic/TopicAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/topic/TopicFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/topic/model/Topic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/fragment/SignOutConfirmFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/shaketopic/shake/model/InterestViewData.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/intro/CardIntroActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
  app/src/main/java/com/teumteum/teumteum/util/AuthUtils.kt
  app/src/main/java/com/teumteum/teumteum/util/ResMapper.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/dialog/CommonDialogConfig.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/dialog/CommonDialogFragment.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/itemdecoration/FlexboxItemDecoration.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/itemdecoration/GridSpacingItemDecoration.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/BackCardView.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/FrontCardView.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/adapter/InterestAdapter.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/model/BackCard.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/model/FrontCard.kt
  app/src/main/java/com/teumteum/teumteum/util/extension/BundleExt.kt
  app/src/main/java/com/teumteum/teumteum/util/extension/FloatExt.kt
  app/src/main/res/drawable-night/ic__system_fill.xml
  app/src/main/res/drawable/ic__system_fill.xml
  app/src/main/res/drawable/ic_card_float.xml
  app/src/main/res/layout/activity_familiar_dialog.xml
  app/src/main/res/layout/activity_shake_topic.xml
  app/src/main/res/layout/fragment_common_dialog.xml
  app/src/main/res/layout/item_interest.xml
  app/src/main/res/values/strings.xml
  core/base/src/main/res/values/attrs.xml
  core/data/src/main/java/com/teumteum/data/interceptor/AuthInterceptor.kt
  gradle/libs.versions.toml
Labels: 우남, FEAT, FIX, UI

#137 [FIX/#136] CommonDialog 취소버튼 색상 수정
  app/src/main/res/layout/fragment_common_dialog.xml
Labels: 우남, FIX, UI

#139 [feat/#138] 카드 뒷면 관심사 삭제/추가 디테일 수정
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/util/callback/OnCurrentListChangedListener.kt
  app/src/main/java/com/teumteum/teumteum/util/callback/SampleClickListener.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/itemdecoration/FlexboxItemDecoration.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/BackCardView.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/adapter/InterestAdapter.kt
  app/src/main/res/drawable-night/ic_plus_fill.xml
  app/src/main/res/drawable/ic_plus_fill.xml
  app/src/main/res/drawable/shape_rect4_color_outline_level01_active.xml
  app/src/main/res/layout/item_interest.xml
Labels: 우남, FEAT, FIX

#140 [feat/#118] main hard push 오류 방지
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
Labels: 민서, DEL, FIX

#141 [FIX/#132] 2차 mvp 배포 전 수정사항 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/AccessLocationActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SocialWebViewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/intro/CardIntroActivity.kt
  app/src/main/res/layout/fragment_common_dialog.xml
  core/domain/src/main/java/com/teumteum/domain/entity/SocialLoginResult.kt
Labels: 세연, FIX

#143 [FIX/#118] 2차 mvp 배포 전 수정사항 반영
  app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimModifyFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimDateTime.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/editCard/EditCardFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/MeetingPagerItems.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/Pager1Content.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/Pager3Content.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/EditCardViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/SettingViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/SingleModalBottomSheet.kt
  app/src/main/java/com/teumteum/teumteum/util/SignupUtils.kt
  core/base/src/main/java/com/teumteum/base/component/compose/theme/Color.kt
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteSettingDataSource.kt
  core/data/src/main/java/com/teumteum/data/repository/SettingRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/SettingService.kt
  core/domain/src/main/java/com/teumteum/domain/repository/SettingRepository.kt
Labels: 민서, DEL, FIX, REFACTOR

#144 [FEAT/#135] 유저 리뷰 기능 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewFinishActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewFriendDetailFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewFriendListAdapter.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewFriendSelectFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewInfoDialog.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewOnboardingActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewViewModel.kt
  app/src/main/res/color/selector_review_text_color.xml
  app/src/main/res/drawable/selector_check_box.xml
  app/src/main/res/drawable/shape_bg_dialog.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/activity_review_finish.xml
  app/src/main/res/layout/activity_review_onboading.xml
  app/src/main/res/layout/dialog_review_info.xml
  app/src/main/res/layout/fragment_review_friend_detail.xml
  app/src/main/res/layout/fragment_review_friend_select.xml
  app/src/main/res/layout/item_review_user.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/last-build.bin
  build-logic/convention/build/kotlin/compileKotlin/local-state/build-history.bin
  build-logic/convention/build/kotlin/conventionjar-classes.txt
  build-logic/convention/build/libs/convention.jar
  core/base/src/main/java/com/teumteum/base/util/extension/ArgsExtension.kt
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
  core/data/src/main/java/com/teumteum/data/model/request/RequestReviewFriend.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseReviewFriend.kt
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/GroupService.kt
  core/domain/src/main/java/com/teumteum/domain/entity/ReviewFriend.kt
  core/domain/src/main/java/com/teumteum/domain/repository/GroupRepository.kt
Labels: 강민 🦖, FEAT, UI

#147 [FEAT] 유저 리뷰 알림과 연결
  app/src/main/java/com/teumteum/teumteum/config/TeumMessagingService.kt
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
  core/domain/src/main/java/com/teumteum/domain/entity/Message.kt
Labels: 세연, FEAT

#151 [FEAT/#150] 유저 리뷰 조회
  app/release/output-metadata.json
  app/src/main/java/com/teumteum/teumteum/presentation/group/join/GroupDetailActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/pager/Pager2Content.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendDetailScreen.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/fragment/RecommendDetailFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/fragment/RecommendFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/RecommendDetailViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/SettingMeetingUiModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/SettingViewModel.kt
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab.keystream
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/file-to-id.tab_i
  build-logic/convention/build/kotlin/compileKotlin/cacheable/caches-jvm/lookups/id-to-file.tab.values.at
  build-logic/convention/build/kotlin/compileKotlin/cacheable/last-build.bin
  build-logic/convention/build/kotlin/compileKotlin/local-state/build-history.bin
  build-logic/convention/build/kotlin/conventionjar-classes.txt
  build-logic/convention/build/libs/convention.jar
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/teumteum/data/model/response/ResponseReview.kt
  core/data/src/main/java/com/teumteum/data/repository/UserRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/UserService.kt
  core/domain/src/main/java/com/teumteum/domain/entity/Review.kt
  core/domain/src/main/java/com/teumteum/domain/repository/UserRepository.kt
Labels: 민서, FEAT

#154 [ FIX/#153] 토큰 리프레시 url 수정
  core/data/src/main/java/com/teumteum/data/interceptor/AuthInterceptor.kt
Labels: 세연, FIX

#155 [SETTING/#152] GithubAction CD Apk 파일 추출 자동화 구현
  .github/workflows/release_builder.yml
Labels: 강민 🦖, FEAT, SETTING

#157 [docs] 오타 수정
  README.md
Labels: 강민 🦖, DOCS

#159 [DOCS/#158] readme 수정
  README.md
Labels: 민서, DOCS

#162 [FIX/#160] 알림 기능 수정
  app/src/main/java/com/teumteum/teumteum/MyApp.kt
  app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt
Labels: 세연, FIX

#164 [FIX/#160] 카드 후면 및 유저 리뷰 수정
  app/src/main/java/com/teumteum/teumteum/config/TeumMessagingService.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewFriendDetailFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/name/GetNameFragment.kt
  app/src/main/java/com/teumteum/teumteum/util/ResMapper.kt
  app/src/main/java/com/teumteum/teumteum/util/custom/view/BackCardView.kt
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/GroupService.kt
Labels: 세연, FIX

#165 [FIX/#160] 유저 리뷰 수정
  app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewViewModel.kt
  core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
  core/data/src/main/java/com/teumteum/data/model/request/RequestReviewFriend.kt
  core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
  core/data/src/main/java/com/teumteum/data/service/GroupService.kt
Labels: 세연, FIX

#167 [ FIX/#166] 푸시알림 동작 방식 변경
  app/src/main/java/com/teumteum/teumteum/config/TeumMessagingService.kt
Labels: 강민 🦖, FIX

#168 [FIX/#158] 2차 mvp QA 오류 수정
  app/src/main/java/com/teumteum/teumteum/config/TeumMessagingService.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimAddress.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimConfirm.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimCreateTopic.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimDateTime.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimFinish.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/compose/MoimPeople.kt
  app/src/main/java/com/teumteum/teumteum/presentation/mypage/recommend/RecommendScreen.kt
  app/src/main/java/com/teumteum/teumteum/util/SignupUtils.kt
  app/src/main/res/drawable-night/ic_heart_default.xml
  app/src/main/res/drawable-night/ic_heart_fill.xml
  app/src/main/res/drawable/ic_heart_default.xml
  app/src/main/res/drawable/ic_heart_fill.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 민서, FIX

#169 [FIX/#160] 알림 수정
  app/src/main/java/com/teumteum/teumteum/presentation/MainActivity.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInViewModel.kt
Labels: 세연, FIX

#171 [FIX/#163] 흔들기 페이지에서 동적으로 생성한 뷰에 할당된 텍스트가 영역을 넘치는 문제 해결
  app/src/main/java/com/teumteum/teumteum/presentation/familiar/shaketopic/shake/InterestView.kt
  app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
  app/src/main/res/layout/item_topic.xml
Labels: 우남, FIX

#172 [Fix/#158] 모임 수정 4자리 입력 오류 수정
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimModifyFragment.kt
  app/src/main/java/com/teumteum/teumteum/presentation/moim/MoimViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 민서, FIX
